### ISSUE TITLE
Shift to SASS/SCSS

### ISSUE THREAD

**Issue by sandyjmacdonald** [sandyjmacdonald/sandyjmacdonald.github.io#2]
Shift to using SASS/SCSS. Need to merge the existing Poole/Lanyon stylesheets.
### Tasks
- [x] Merge the existing Poole/Lanyon stylesheets.
- [ ] Add SASS variables, partials (use a partial for the syntax styles), mixins.
- [ ] Try out Grunt for compiling the SCSS to CSS and minifying CSS/images/etc.
